// Auto-generated by scripts/embed-wasm.mjs — DO NOT EDIT

import { WebTreeSitterWasm } from './web_tree_sitter.js';
import { JavascriptWasm } from './javascript.js';
import { TypescriptWasm } from './typescript.js';
import { TsxWasm } from './tsx.js';
import { PythonWasm } from './python.js';
import { JavaWasm } from './java.js';
import { CSharpWasm } from './c_sharp.js';
import { CppWasm } from './cpp.js';
import { GoWasm } from './go.js';
import { RustWasm } from './rust.js';
import { PhpWasm } from './php.js';
import { PhpOnlyWasm } from './php_only.js';
import { RubyWasm } from './ruby.js';

/** Grammar WASM files keyed by snake_case identifier. */
export const grammarWasm: Record<string, string> = {
  'tree_sitter_javascript': JavascriptWasm,
  'tree_sitter_typescript': TypescriptWasm,
  'tree_sitter_tsx': TsxWasm,
  'tree_sitter_python': PythonWasm,
  'tree_sitter_java': JavaWasm,
  'tree_sitter_c_sharp': CSharpWasm,
  'tree_sitter_cpp': CppWasm,
  'tree_sitter_go': GoWasm,
  'tree_sitter_rust': RustWasm,
  'tree_sitter_php': PhpWasm,
  'tree_sitter_php_only': PhpOnlyWasm,
  'tree_sitter_ruby': RubyWasm,
};

/** Runtime WASM binary for web-tree-sitter. */
export const runtimeWasm: string = WebTreeSitterWasm;

interface WasmGrammarEntry {
  varName: string;
  exportName: string;
  pkg: string;
  sizeKB: string;
}

const WASM_GRAMMAR_REGISTRY: WasmGrammarEntry[] = [
  {
    "varName": "WebTreeSitterWasm",
    "exportName": "web_tree_sitter",
    "pkg": "web-tree-sitter",
    "sizeKB": "192.2"
  },
  {
    "varName": "JavascriptWasm",
    "exportName": "javascript",
    "pkg": "tree-sitter-javascript",
    "sizeKB": "350.5"
  },
  {
    "varName": "TypescriptWasm",
    "exportName": "typescript",
    "pkg": "tree-sitter-typescript",
    "sizeKB": "1380.7"
  },
  {
    "varName": "TsxWasm",
    "exportName": "tsx",
    "pkg": "tree-sitter-typescript",
    "sizeKB": "1411.8"
  },
  {
    "varName": "PythonWasm",
    "exportName": "python",
    "pkg": "tree-sitter-python",
    "sizeKB": "444.8"
  },
  {
    "varName": "JavaWasm",
    "exportName": "java",
    "pkg": "tree-sitter-java",
    "sizeKB": "404.9"
  },
  {
    "varName": "CSharpWasm",
    "exportName": "c_sharp",
    "pkg": "tree-sitter-c-sharp",
    "sizeKB": "5787.9"
  },
  {
    "varName": "CppWasm",
    "exportName": "cpp",
    "pkg": "tree-sitter-cpp",
    "sizeKB": "3354.4"
  },
  {
    "varName": "GoWasm",
    "exportName": "go",
    "pkg": "tree-sitter-go",
    "sizeKB": "205.1"
  },
  {
    "varName": "RustWasm",
    "exportName": "rust",
    "pkg": "tree-sitter-rust",
    "sizeKB": "1004.5"
  },
  {
    "varName": "PhpWasm",
    "exportName": "php",
    "pkg": "tree-sitter-php",
    "sizeKB": "785.2"
  },
  {
    "varName": "PhpOnlyWasm",
    "exportName": "php_only",
    "pkg": "tree-sitter-php",
    "sizeKB": "739.5"
  },
  {
    "varName": "RubyWasm",
    "exportName": "ruby",
    "pkg": "tree-sitter-ruby",
    "sizeKB": "2057.0"
  }
];
