import { Parser, Language } from 'web-tree-sitter';
import { SupportedLanguages } from 'gitnexus-shared';
import { LoggerProviderRegistry } from '../config/LoggerProviderRegistry.js';
const logger = LoggerProviderRegistry.get();
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { grammarWasm, runtimeWasm } from './wasm/index.js';

// ── WASM grammar constants (auto-generated by scripts/embed-wasm.mjs) ──────
// Regenerate: cd gitnexus && node scripts/embed-wasm.mjs

const WASM_GRAMMARS: Record<string, string> = {
  'tree-sitter-javascript.wasm': grammarWasm['tree_sitter_javascript'],
  'tree-sitter-typescript.wasm': grammarWasm['tree_sitter_typescript'],
  'tree-sitter-tsx.wasm': grammarWasm['tree_sitter_tsx'],
  'tree-sitter-python.wasm': grammarWasm['tree_sitter_python'],
  'tree-sitter-java.wasm': grammarWasm['tree_sitter_java'],
  'tree-sitter-c_sharp.wasm': grammarWasm['tree_sitter_c_sharp'],
  'tree-sitter-cpp.wasm': grammarWasm['tree_sitter_cpp'],
  'tree-sitter-go.wasm': grammarWasm['tree_sitter_go'],
  'tree-sitter-rust.wasm': grammarWasm['tree_sitter_rust'],
  'tree-sitter-php_only.wasm': grammarWasm['tree_sitter_php_only'],
  'tree-sitter-ruby.wasm': grammarWasm['tree_sitter_ruby'],
  'web-tree-sitter.wasm': runtimeWasm,
};

// ── Language key → WASM file name mapping ──────────────────────────────────
// Keys align with SupportedLanguages enum values from gitnexus-shared.

const LANGUAGE_WASM_MAP: Record<string, string> = {
  [SupportedLanguages.JavaScript]: 'tree-sitter-javascript.wasm',
  [SupportedLanguages.TypeScript]: 'tree-sitter-typescript.wasm',
  [`${SupportedLanguages.TypeScript}:tsx`]: 'tree-sitter-tsx.wasm',
  [SupportedLanguages.Python]: 'tree-sitter-python.wasm',
  [SupportedLanguages.Java]: 'tree-sitter-java.wasm',
  [SupportedLanguages.CSharp]: 'tree-sitter-c_sharp.wasm',
  'c#': 'tree-sitter-c_sharp.wasm',
  [SupportedLanguages.CPlusPlus]: 'tree-sitter-cpp.wasm',
  'c++': 'tree-sitter-cpp.wasm',
  [SupportedLanguages.Go]: 'tree-sitter-go.wasm',
  [SupportedLanguages.Rust]: 'tree-sitter-rust.wasm',
  [SupportedLanguages.PHP]: 'tree-sitter-php_only.wasm',
  [SupportedLanguages.Ruby]: 'tree-sitter-ruby.wasm',
  [SupportedLanguages.Vue]: 'tree-sitter-typescript.wasm',
};

// ── Runtime state ──────────────────────────────────────────────────────────

let initialized = false;
const languageCache = new Map<string, Language>();
let sharedParser: Parser | null = null;

// ── WASM runtime initialization ────────────────────────────────────────────

/**
 * Initialize web-tree-sitter WASM runtime.
 * Must be called once before any grammar loading.
 *
 * Resolution order:
 *   1. Embedded `web-tree-sitter.wasm` from `WASM_GRAMMARS` base64 constant
 *   2. `node_modules/web-tree-sitter/web-tree-sitter.wasm` via `fs.readFileSync`
 *   3. Default `Parser.init()` — lets web-tree-sitter locate its own WASM
 */
export async function initWasmRuntime(): Promise<void> {
  if (initialized) return;

  // 1. Embedded WASM runtime
  const embeddedB64 = WASM_GRAMMARS['web-tree-sitter.wasm'];
  if (embeddedB64) {
    try {
      const wasmBytes = Buffer.from(embeddedB64, 'base64');
      await Parser.init({ wasmBinary: wasmBytes });
      initialized = true;
      return;
    } catch (err) {
      logger.warn({ err }, 'Failed to load embedded web-tree-sitter.wasm, trying fallback');
    }
  }

  // 2. node_modules filesystem fallback
  try {
    const wasmPath = join(
      process.cwd(),
      'node_modules',
      'web-tree-sitter',
      'web-tree-sitter.wasm',
    );
    if (existsSync(wasmPath)) {
      const wasmBytes = readFileSync(wasmPath);
      await Parser.init({ wasmBinary: wasmBytes });
      initialized = true;
      return;
    }
  } catch (err) {
    logger.warn(
      { err },
      'Failed to load web-tree-sitter.wasm from node_modules, trying default init',
    );
  }

  // 3. Default init — lets web-tree-sitter find its own WASM
  try {
    await Parser.init();
    initialized = true;
  } catch (err) {
    logger.error({ err }, 'web-tree-sitter Parser.init() failed');
    throw err;
  }
}

// ── Grammar loading ────────────────────────────────────────────────────────

/**
 * Load a grammar Language from embedded WASM bytes.
 *
 * @param languageKey - Key from `LANGUAGE_WASM_MAP` (e.g. `'javascript'`, `'typescript:tsx'`)
 * @returns The loaded `Language`, or `null` if the grammar is not available
 */
export async function loadWasmGrammar(languageKey: string): Promise<Language | null> {
  await initWasmRuntime();

  const cached = languageCache.get(languageKey);
  if (cached) return cached;

  const wasmFile = LANGUAGE_WASM_MAP[languageKey];
  if (!wasmFile) {
    logger.warn({ languageKey }, 'No WASM grammar mapping for language key');
    return null;
  }

  const b64 = WASM_GRAMMARS[wasmFile];
  if (!b64) {
    logger.warn({ wasmFile }, 'WASM grammar not embedded');
    return null;
  }

  try {
    const wasmBytes = Buffer.from(b64, 'base64');
    const language = await Language.load(wasmBytes);
    languageCache.set(languageKey, language);
    return language;
  } catch (err) {
    logger.error({ err, wasmFile, languageKey }, 'Failed to load WASM grammar');
    return null;
  }
}

// ── Availability checks ────────────────────────────────────────────────────

/**
 * Check if a WASM grammar is available (embedded) for the given language key.
 *
 * @param languageKey - Key from `LANGUAGE_WASM_MAP`
 * @returns `true` if the WASM grammar is embedded and ready to load
 */
export function isWasmGrammarAvailable(languageKey: string): boolean {
  const wasmFile = LANGUAGE_WASM_MAP[languageKey];
  if (!wasmFile) return false;
  return WASM_GRAMMARS[wasmFile] != null;
}

// ── Parser creation ────────────────────────────────────────────────────────


