/**
 * embed-wasm.mjs — Reads .wasm files from tree-sitter grammar packages
 * and generates TypeScript files with base64-encoded bytes for embedding.
 *
 * Usage: node scripts/embed-wasm.mjs
 *
 * Output: src/core/tree-sitter/wasm/*.ts  (one per grammar)
 *         src/core/tree-sitter/wasm/index.ts  (registry of all)
 */
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const _require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'core', 'tree-sitter', 'wasm');

// Package name → { wasmFile, exportName, variants? }
// Variants: some packages expose multiple grammars (e.g. php + php_only, typescript + tsx)
const GRAMMAR_MAP = {
  'web-tree-sitter': { wasmFile: 'web-tree-sitter.wasm', exportName: 'web_tree_sitter' },
  'tree-sitter-javascript': { wasmFile: 'tree-sitter-javascript.wasm', exportName: 'javascript' },
  'tree-sitter-typescript': {
    wasmFile: 'tree-sitter-typescript.wasm',
    exportName: 'typescript',
    variants: [
      { wasmFile: 'tree-sitter-tsx.wasm', exportName: 'tsx' },
    ],
  },
  'tree-sitter-python': { wasmFile: 'tree-sitter-python.wasm', exportName: 'python' },
  'tree-sitter-java': { wasmFile: 'tree-sitter-java.wasm', exportName: 'java' },
  'tree-sitter-c-sharp': { wasmFile: 'tree-sitter-c_sharp.wasm', exportName: 'c_sharp' },
  'tree-sitter-cpp': { wasmFile: 'tree-sitter-cpp.wasm', exportName: 'cpp' },
  'tree-sitter-go': { wasmFile: 'tree-sitter-go.wasm', exportName: 'go' },
  'tree-sitter-rust': { wasmFile: 'tree-sitter-rust.wasm', exportName: 'rust' },
  'tree-sitter-php': {
    wasmFile: 'tree-sitter-php.wasm',
    exportName: 'php',
    variants: [
      { wasmFile: 'tree-sitter-php_only.wasm', exportName: 'php_only' },
    ],
  },
  'tree-sitter-ruby': { wasmFile: 'tree-sitter-ruby.wasm', exportName: 'ruby' },
};

function getPackageRoot(pkgName) {
  let mainPath;
  try {
    mainPath = path.dirname(_require.resolve(pkgName + '/package.json'));
  } catch {
    // Some packages don't export package.json (e.g. web-tree-sitter).
    // Resolve from the package's main entry point.
    mainPath = path.dirname(_require.resolve(pkgName));
  }
  let dir = mainPath;
  while (dir) {
    const pj = path.join(dir, 'package.json');
    if (fs.existsSync(pj)) {
      const pkg = JSON.parse(fs.readFileSync(pj, 'utf-8'));
      if (pkg.name === pkgName) return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return mainPath;
}

function toPascalCase(str) {
  return str
    .split(/[_-]/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function encodeWasm(filePath) {
  const wasmBytes = fs.readFileSync(filePath);
  const b64 = wasmBytes.toString('base64');
  const sizeKB = (wasmBytes.length / 1024).toFixed(1);
  return { b64, sizeBytes: wasmBytes.length, sizeKB };
}

// Ensure output dir
fs.mkdirSync(OUT, { recursive: true });

const registry = [];

for (const [pkg, config] of Object.entries(GRAMMAR_MAP)) {
  const rootDir = getPackageRoot(pkg);
  const allEntries = [config, ...(config.variants || [])];

  for (const entry of allEntries) {
    const wasmPath = path.join(rootDir, entry.wasmFile);
    const { b64, sizeBytes, sizeKB } = encodeWasm(wasmPath);
    const varName = toPascalCase(entry.exportName) + 'Wasm';

    const outFile = path.join(OUT, `${entry.exportName}.ts`);
    const content = `// Auto-generated by scripts/embed-wasm.mjs
// Source: ${pkg} (${entry.wasmFile}) — ${sizeKB} KB

export const ${varName} = '${b64}';
`;

    fs.writeFileSync(outFile, content);
    console.log(`Generated: ${outFile} (${sizeKB} KB base64)`);

    registry.push({ varName, exportName: entry.exportName, pkg, sizeKB });
  }
}

// Generate index.ts
const grammarEntries = registry.filter(r => r.exportName !== 'web_tree_sitter');
const runtimeEntry = registry.find(r => r.exportName === 'web_tree_sitter');

const importLines = registry.map(r => {
  const modPath = `./${r.exportName}.js`;
  return `import { ${r.varName} } from '${modPath}';`;
});

const grammarMapLines = grammarEntries.map(r => {
  // Convert PascalCase varName to snake_case key: CSharpWasm → tree_sitter_c_sharp
  const key = 'tree_sitter_' + r.exportName;
  return `  '${key}': ${r.varName},`;
});

const indexContent = `// Auto-generated by scripts/embed-wasm.mjs — DO NOT EDIT

${importLines.join('\n')}

/** Grammar WASM files keyed by snake_case identifier. */
export const grammarWasm: Record<string, string> = {
${grammarMapLines.join('\n')}
};

/** Runtime WASM binary for web-tree-sitter. */
export const runtimeWasm: string = ${runtimeEntry ? runtimeEntry.varName : "''"};

export interface WasmGrammarEntry {
  varName: string;
  exportName: string;
  pkg: string;
  sizeKB: string;
}

export const WASM_GRAMMAR_REGISTRY: WasmGrammarEntry[] = ${JSON.stringify(registry, null, 2)};
`;

fs.writeFileSync(path.join(OUT, 'index.ts'), indexContent);
console.log(`\nGenerated: ${path.join(OUT, 'index.ts')}`);

// Total size
const totalBytes = registry.reduce((sum, r) => sum + parseFloat(r.sizeKB), 0);
console.log(`\nTotal embedded WASM: ~${totalBytes.toFixed(1)} KB`);
console.log(`Exports: ${registry.map(r => r.varName).join(', ')}`);
console.log('\nDone.');
